version: '3.8'
services:
  db:
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  api:
    build: .
    restart: always
    ports:
      - '3009:3000'
    env_file:
      - .env
    #depends_on:
    #  - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - mad-network

volumes:
  db:
    driver: local

networks:
  mad-network:
    name: mad-network
