version: '3.8'
services:
  db:
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  api:
    build: .
    restart: always
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mad
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db:
    driver: local